version: 2

updates:
  - package-ecosystem: maven
    directory: "/service/backend"
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: "/service/auth-service"
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: "/service/gateway"
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
