# SPRING_PROFILES_ACTIVE=dev outside a container.

logging.level.root=INFO
logging.level.centuryroad=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

spring.devtools.restart.enabled=true
